platform selector class implementation
AshAswin/Adaptive-Deployment-of-Safety-Monitors-of-Autonomous-Systems pull request #14
Opened 2020-06-07 21:33 UTC by Manojkl

2020-06-10 06:46 UTC, AshAswin commented on platform_selector.py
> +        self.__platform = SafetyMonitor.NO_SELECTION
self.__platform is of custom datatype Platforms. Check custom_dtypes

2020-06-10 06:47 UTC, AshAswin commented on platform_selector.py
> +
Extra line

2020-06-10 06:50 UTC, AshAswin commented on platform_selector.py
> +        self.__repo_image.update_current_safety_monitor(self.platform)
self.__repo_image.update_platform_status has to be used. Wrong method. platform is a private attribute

2020-06-10 06:51 UTC, AshAswin commented on platform_selector.py
> +        return u
Add Newline in the end of the file

2020-06-10 06:53 UTC, AshAswin commented on platform_selector.py
> +        platforms = Model("./platforms.mzn")
Better to have platforms.mzn path as a command-line argument

2020-06-10 06:55 UTC, AshAswin commented on platform_selector.py
> +        instance["name"] = 1
Shall we consider a better place to store these thresholds, instead of hardcoding inside this method

2020-06-10 06:56 UTC, AshAswin commented on platform_selector.py
> +    def platform_selected(self):
This method has to be private

2020-06-10 06:57 UTC, AshAswin commented on platform_selector.py
> +        for i in result_intermediate:
Shall we use a single liner instead of this for loop? More Pythonic

2020-06-10 06:58 UTC, AshAswin commented on platform_selector.py
> +    def __init__(self, Repository):
Better to follow lower snake case letters for method arguments like "Repository"

2020-06-10 06:59 UTC, AshAswin commented on platform_selector.py
> +# print(driver.platform_selected())
Please remove unused code

2020-06-10 07:01 UTC, AshAswin requested changes
Please make the changes mentioned in the review. This code will not work as it has syntax errors. You will have to consider adding necessary comments to classes /wherever required.

2020-06-21 04:44 UTC, AshAswin requested changes
Please remove this branch and Pull Request incase you are not using it.

2020-06-21 08:36 UTC, closed without merging

2020-06-21 08:38 UTC, Manojkl commented
Changes to platform selector is updated with jithin pull request